import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import styles from './home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RocketBlog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <main>
        <div className={styles.landing}>
          <div className={styles.content}>
            <div>
              <h1>
                Veja o guia definitivo para conquistar seus objetivos como DEV em 2022
              </h1>

              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique placerat hac. 
              </p>

              <Link href="#">
                <a>
                  Veja mais
                  <img src="/arrow-right.svg" alt="Veja mais" />
                </a>
              </Link>
            </div>
            <img src="/featured-image.png" alt="Código" />
          </div>
        </div>

        <div className={styles.posts}>
          <Link href="#">
            <a className={styles.post}>
              <img src="/post-1.png" alt="Começando no ReactJS em 2022" />
              <time>04 de janeiro de 2022</time>
              <h1>Começando no ReactJS em 2022</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique. Sed volutpat aenean.</p>
            </a>
          </Link>
          <Link href="#">
            <a className={styles.post}>
              <img src="/post-2.png" alt="10 dicas para conseguir a vaga desejada" />
              <time>04 de janeiro de 2022</time>
              <h1>10 dicas para conseguir a vaga desejada</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique. Sed volutpat aenean.</p>
            </a>
          </Link>
          <Link href="#">
            <a className={styles.post}>
              <img src="/post-2.png" alt="10 dicas para conseguir a vaga desejada" />
              <time>04 de janeiro de 2022</time>
              <h1>10 dicas para conseguir a vaga desejada</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique. Sed volutpat aenean.</p>
            </a>
          </Link>
        </div>
        <div className={styles.posts}>
          <Link href="#">
            <a className={styles.post}>
              <img src="/post-1.png" alt="Começando no ReactJS em 2022" />
              <time>04 de janeiro de 2022</time>
              <h1>Começando no ReactJS em 2022</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique. Sed volutpat aenean.</p>
            </a>
          </Link>
          <Link href="#">
            <a className={styles.post}>
              <img src="/post-2.png" alt="10 dicas para conseguir a vaga desejada" />
              <time>04 de janeiro de 2022</time>
              <h1>10 dicas para conseguir a vaga desejada</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique. Sed volutpat aenean.</p>
            </a>
          </Link>
          <Link href="#">
            <a className={styles.post}>
              <img src="/post-2.png" alt="10 dicas para conseguir a vaga desejada" />
              <time>04 de janeiro de 2022</time>
              <h1>10 dicas para conseguir a vaga desejada</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique. Sed volutpat aenean.</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home;
